# Generated by Django 4.1.5 on 2023-03-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookupmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
