# Generated by Django 4.1.5 on 2023-03-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_alter_bookupmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookupmodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
